[versions]
kotlin = "2.3.10"
springBoot = "4.0.3"
springDependencyManagement = "1.1.7"
openapiGenerator = "7.11.0"
htmx = "2.0.4"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Databases
h2 = { module = "com.h2database:h2" }
postgresql = { module = "org.postgresql:postgresql" }
mysql = { module = "com.mysql:mysql-connector-j" }

# Flyway
flyway-core = { module = "org.flywaydb:flyway-core" }

# Webjars for UI
webjars-htmx = { module = "org.webjars.npm:htmx.org", version.ref = "htmx" }

# OpenAPI Gen dependencies
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version = "2.2.27" }
springfox-swagger2 = { module = "io.springfox:springfox-swagger2", version = "3.0.0" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapiGenerator" }
graalvm-buildtools = { id = "org.graalvm.buildtools.native", version = "0.10.4" }
